# Generated by Django 3.0.4 on 2020-04-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('emi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('dob', models.DateField(blank=True)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('employed', models.CharField(max_length=150)),
                ('salary', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('dependency', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
