# Generated by Django 2.2.6 on 2020-04-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='emi',
        ),
        migrations.AddField(
            model_name='loans',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
