# Generated by Django 2.2.6 on 2020-04-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visitedloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='type',
            field=models.CharField(choices=[('HM', 'Home'), ('PR', 'Personal'), ('BS', 'Bussiness')], max_length=100, null=True),
        ),
    ]
