# Generated by Django 2.2.6 on 2020-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200404_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedloan',
            name='timevisited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
